version: '3.9'
services:
  halo:
    image: halohub/halo
    ports:
      - 8090:8090
    volumes:
      - ./halo-data:/root/.halo

  # halo-theme:
  #   image: halo-theme-sakura
  #   ports:
  #     - 9557:9556
  #   env_file:
  #     - .env
  #   depends_on:
  #     - halo
